name: release

on:
  release:
    types: published

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Azure/docker-login@v1
        with:
          username: '${{ secrets.SMA_CONTAINER_REGISTRY_USER }}'
          password: '${{ secrets.SMA_CONTAINER_REGISTRY_PASS }}'
          login-server: '${{ secrets.SMA_CONTAINER_REGISTRY }}'
      - run: |
          docker build . -t ${{ secrets.SMA_CONTAINER_REGISTRY }}/helpsmatechnologies:latest
          docker push ${{ secrets.SMA_CONTAINER_REGISTRY }}/helpsmatechnologies:latest
